# Generated by Django 3.0.4 on 2020-10-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='closed',
        ),
    ]
