# Generated by Django 3.0.4 on 2020-10-04 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchlist_user',
            field=models.ManyToManyField(blank=True, related_name='watchlist_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
