# Generated by Django 3.0.4 on 2020-10-07 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_on',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.Listings'),
        ),
    ]
