# Generated by Django 3.0.4 on 2020-10-07 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201008_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_made_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Listings'),
        ),
    ]
